
project_name: kscribbler

builds:
  - id: kscribbler
    dir: .
    main: ./cmd/kscribbler
    binary: kscribbler
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    ldflags: "-s -w"

archives:
  - format: tar.gz
    name_template: KoboRoot
    files:
      - etc/udev/rules.d/98-kscribbler.rules
      - mnt/onboard/.adds/nm/kscribbler
      - opt/bin/kscribbler
    replacements:
      linux: ""
    wrap_in_directory: true

nfpms:
  - package_name: kscribbler

release:
  draft: true
  prerelease: false
