---
version: 2

project_name: kscribbler

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/kscribbler
    binary: kscribbler
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
archives:
  - id: kobo
    name_template: KoboRoot
    formats: tar.gz
    wrap_in_directory: false
    meta: true
    files:
      - none*
      - src: ./packaging/KoboRoot
        dst: ./
      - src: ./dist/kscribbler*/kscribbler
        dst: ./opt/bin

release:
  draft: true

checksum:
  name_template: "checksums.txt"
